package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Dangnhap generated by hbm2java
 */
public class Dangnhap  implements java.io.Serializable {


     private Serializable username;
     private Nhanvien nhanvien;
     private Serializable passwords;
     private Serializable chucvu;

    public Dangnhap() {
    }

	
    public Dangnhap(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Dangnhap(Nhanvien nhanvien, Serializable passwords, Serializable chucvu) {
       this.nhanvien = nhanvien;
       this.passwords = passwords;
       this.chucvu = chucvu;
    }
   
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Serializable getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(Serializable passwords) {
        this.passwords = passwords;
    }
    public Serializable getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Serializable chucvu) {
        this.chucvu = chucvu;
    }




}


