package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1



/**
 * Hoadonchitiet generated by hbm2java
 */
public class Hoadonchitiet  implements java.io.Serializable {


     private int mahdct;
     private Hoadon hoadon;
     private Laptop laptop;
     private Integer soluong;

    public Hoadonchitiet() {
    }

	
    public Hoadonchitiet(int mahdct, Hoadon hoadon, Laptop laptop) {
        this.mahdct = mahdct;
        this.hoadon = hoadon;
        this.laptop = laptop;
    }
    public Hoadonchitiet(int mahdct, Hoadon hoadon, Laptop laptop, Integer soluong) {
       this.mahdct = mahdct;
       this.hoadon = hoadon;
       this.laptop = laptop;
       this.soluong = soluong;
    }
   
    public int getMahdct() {
        return this.mahdct;
    }
    
    public void setMahdct(int mahdct) {
        this.mahdct = mahdct;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }
    public Laptop getLaptop() {
        return this.laptop;
    }
    
    public void setLaptop(Laptop laptop) {
        this.laptop = laptop;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }




}


