package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private Serializable makh;
     private Serializable tenkh;
     private Serializable dienthoai;
     private Set hoadons = new HashSet(0);

    public Khachhang() {
    }

	
    public Khachhang(Serializable makh) {
        this.makh = makh;
    }
    public Khachhang(Serializable makh, Serializable tenkh, Serializable dienthoai, Set hoadons) {
       this.makh = makh;
       this.tenkh = tenkh;
       this.dienthoai = dienthoai;
       this.hoadons = hoadons;
    }
   
    public Serializable getMakh() {
        return this.makh;
    }
    
    public void setMakh(Serializable makh) {
        this.makh = makh;
    }
    public Serializable getTenkh() {
        return this.tenkh;
    }
    
    public void setTenkh(Serializable tenkh) {
        this.tenkh = tenkh;
    }
    public Serializable getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(Serializable dienthoai) {
        this.dienthoai = dienthoai;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


