package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Laptop generated by hbm2java
 */
public class Laptop  implements java.io.Serializable {


     private Serializable malaptop;
     private Hanglaptop hanglaptop;
     private Nhacungcap nhacungcap;
     private Serializable tenlaptop;
     private Integer soluong;
     private Date ngaynhap;
     private Integer giatien;
     private Set hoadonchitiets = new HashSet(0);

    public Laptop() {
    }

	
    public Laptop(Serializable malaptop, Hanglaptop hanglaptop, Nhacungcap nhacungcap) {
        this.malaptop = malaptop;
        this.hanglaptop = hanglaptop;
        this.nhacungcap = nhacungcap;
    }
    public Laptop(Serializable malaptop, Hanglaptop hanglaptop, Nhacungcap nhacungcap, Serializable tenlaptop, Integer soluong, Date ngaynhap, Integer giatien, Set hoadonchitiets) {
       this.malaptop = malaptop;
       this.hanglaptop = hanglaptop;
       this.nhacungcap = nhacungcap;
       this.tenlaptop = tenlaptop;
       this.soluong = soluong;
       this.ngaynhap = ngaynhap;
       this.giatien = giatien;
       this.hoadonchitiets = hoadonchitiets;
    }
   
    public Serializable getMalaptop() {
        return this.malaptop;
    }
    
    public void setMalaptop(Serializable malaptop) {
        this.malaptop = malaptop;
    }
    public Hanglaptop getHanglaptop() {
        return this.hanglaptop;
    }
    
    public void setHanglaptop(Hanglaptop hanglaptop) {
        this.hanglaptop = hanglaptop;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Serializable getTenlaptop() {
        return this.tenlaptop;
    }
    
    public void setTenlaptop(Serializable tenlaptop) {
        this.tenlaptop = tenlaptop;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Date getNgaynhap() {
        return this.ngaynhap;
    }
    
    public void setNgaynhap(Date ngaynhap) {
        this.ngaynhap = ngaynhap;
    }
    public Integer getGiatien() {
        return this.giatien;
    }
    
    public void setGiatien(Integer giatien) {
        this.giatien = giatien;
    }
    public Set getHoadonchitiets() {
        return this.hoadonchitiets;
    }
    
    public void setHoadonchitiets(Set hoadonchitiets) {
        this.hoadonchitiets = hoadonchitiets;
    }




}


