package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap  implements java.io.Serializable {


     private Serializable manhacungcap;
     private Serializable tennhacungcap;
     private Serializable diachi;
     private Serializable dienthoai;
     private Set laptops = new HashSet(0);

    public Nhacungcap() {
    }

	
    public Nhacungcap(Serializable manhacungcap) {
        this.manhacungcap = manhacungcap;
    }
    public Nhacungcap(Serializable manhacungcap, Serializable tennhacungcap, Serializable diachi, Serializable dienthoai, Set laptops) {
       this.manhacungcap = manhacungcap;
       this.tennhacungcap = tennhacungcap;
       this.diachi = diachi;
       this.dienthoai = dienthoai;
       this.laptops = laptops;
    }
   
    public Serializable getManhacungcap() {
        return this.manhacungcap;
    }
    
    public void setManhacungcap(Serializable manhacungcap) {
        this.manhacungcap = manhacungcap;
    }
    public Serializable getTennhacungcap() {
        return this.tennhacungcap;
    }
    
    public void setTennhacungcap(Serializable tennhacungcap) {
        this.tennhacungcap = tennhacungcap;
    }
    public Serializable getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(Serializable diachi) {
        this.diachi = diachi;
    }
    public Serializable getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(Serializable dienthoai) {
        this.dienthoai = dienthoai;
    }
    public Set getLaptops() {
        return this.laptops;
    }
    
    public void setLaptops(Set laptops) {
        this.laptops = laptops;
    }




}


