package entities;
// Generated Nov 20, 2019 8:29:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private Serializable manv;
     private Serializable tennv;
     private Date ngaysinh;
     private Integer sodienthoai;
     private Integer luong;
     private Serializable diachi;
     private Serializable chucvu;
     private Dangnhap dangnhap;
     private Set hoadons = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(Serializable manv) {
        this.manv = manv;
    }
    public Nhanvien(Serializable manv, Serializable tennv, Date ngaysinh, Integer sodienthoai, Integer luong, Serializable diachi, Serializable chucvu, Dangnhap dangnhap, Set hoadons) {
       this.manv = manv;
       this.tennv = tennv;
       this.ngaysinh = ngaysinh;
       this.sodienthoai = sodienthoai;
       this.luong = luong;
       this.diachi = diachi;
       this.chucvu = chucvu;
       this.dangnhap = dangnhap;
       this.hoadons = hoadons;
    }
   
    public Serializable getManv() {
        return this.manv;
    }
    
    public void setManv(Serializable manv) {
        this.manv = manv;
    }
    public Serializable getTennv() {
        return this.tennv;
    }
    
    public void setTennv(Serializable tennv) {
        this.tennv = tennv;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public Integer getSodienthoai() {
        return this.sodienthoai;
    }
    
    public void setSodienthoai(Integer sodienthoai) {
        this.sodienthoai = sodienthoai;
    }
    public Integer getLuong() {
        return this.luong;
    }
    
    public void setLuong(Integer luong) {
        this.luong = luong;
    }
    public Serializable getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(Serializable diachi) {
        this.diachi = diachi;
    }
    public Serializable getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Serializable chucvu) {
        this.chucvu = chucvu;
    }
    public Dangnhap getDangnhap() {
        return this.dangnhap;
    }
    
    public void setDangnhap(Dangnhap dangnhap) {
        this.dangnhap = dangnhap;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


