package entities;
// Generated Nov 26, 2019 8:49:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hanglaptop generated by hbm2java
 */
public class Hanglaptop  implements java.io.Serializable {


     private String mahang;
     private String tenhang;
     private Set laptops = new HashSet(0);

    public Hanglaptop() {
    }

	
    public Hanglaptop(String mahang) {
        this.mahang = mahang;
    }
    public Hanglaptop(String mahang, String tenhang, Set laptops) {
       this.mahang = mahang;
       this.tenhang = tenhang;
       this.laptops = laptops;
    }
   
    public String getMahang() {
        return this.mahang;
    }
    
    public void setMahang(String mahang) {
        this.mahang = mahang;
    }
    public String getTenhang() {
        return this.tenhang;
    }
    
    public void setTenhang(String tenhang) {
        this.tenhang = tenhang;
    }
    public Set getLaptops() {
        return this.laptops;
    }
    
    public void setLaptops(Set laptops) {
        this.laptops = laptops;
    }




}


