package entities;
// Generated Nov 26, 2019 8:49:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String manv;
     private String tennv;
     private Date ngaysinh;
     private Integer sodienthoai;
     private Integer luong;
     private String diachi;
     private String gioitinh;
     private Dangnhap dangnhap;
     private Set hoadons = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(String manv) {
        this.manv = manv;
    }
    public Nhanvien(String manv, String tennv, Date ngaysinh, Integer sodienthoai, Integer luong, String diachi, String gioitinh, Dangnhap dangnhap, Set hoadons) {
       this.manv = manv;
       this.tennv = tennv;
       this.ngaysinh = ngaysinh;
       this.sodienthoai = sodienthoai;
       this.luong = luong;
       this.diachi = diachi;
       this.gioitinh = gioitinh;
       this.dangnhap = dangnhap;
       this.hoadons = hoadons;
    }
   
    public String getManv() {
        return this.manv;
    }
    
    public void setManv(String manv) {
        this.manv = manv;
    }
    public String getTennv() {
        return this.tennv;
    }
    
    public void setTennv(String tennv) {
        this.tennv = tennv;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public Integer getSodienthoai() {
        return this.sodienthoai;
    }
    
    public void setSodienthoai(Integer sodienthoai) {
        this.sodienthoai = sodienthoai;
    }
    public Integer getLuong() {
        return this.luong;
    }
    
    public void setLuong(Integer luong) {
        this.luong = luong;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public Dangnhap getDangnhap() {
        return this.dangnhap;
    }
    
    public void setDangnhap(Dangnhap dangnhap) {
        this.dangnhap = dangnhap;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


