package model;
// Generated Nov 27, 2019 7:49:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap  implements java.io.Serializable {


     private String manhacungcap;
     private String tennhacungcap;
     private String diachi;
     private String dienthoai;
     private Set<Laptop> laptops = new HashSet<Laptop>(0);

    public Nhacungcap() {
    }

	
    public Nhacungcap(String manhacungcap) {
        this.manhacungcap = manhacungcap;
    }
    public Nhacungcap(String manhacungcap, String tennhacungcap, String diachi, String dienthoai, Set<Laptop> laptops) {
       this.manhacungcap = manhacungcap;
       this.tennhacungcap = tennhacungcap;
       this.diachi = diachi;
       this.dienthoai = dienthoai;
       this.laptops = laptops;
    }
   
    public String getManhacungcap() {
        return this.manhacungcap;
    }
    
    public void setManhacungcap(String manhacungcap) {
        this.manhacungcap = manhacungcap;
    }
    public String getTennhacungcap() {
        return this.tennhacungcap;
    }
    
    public void setTennhacungcap(String tennhacungcap) {
        this.tennhacungcap = tennhacungcap;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public Set<Laptop> getLaptops() {
        return this.laptops;
    }
    
    public void setLaptops(Set<Laptop> laptops) {
        this.laptops = laptops;
    }




}


