package model;
// Generated Nov 25, 2019 8:40:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hanglaptop generated by hbm2java
 */
public class Hanglaptop  implements java.io.Serializable {


     private String mahang;
     private String tenhang;
     private Set<Laptop> laptops = new HashSet<Laptop>(0);

    public Hanglaptop() {
    }

	
    public Hanglaptop(String mahang) {
        this.mahang = mahang;
    }
    public Hanglaptop(String mahang, String tenhang, Set<Laptop> laptops) {
       this.mahang = mahang;
       this.tenhang = tenhang;
       this.laptops = laptops;
    }
   
    public String getMahang() {
        return this.mahang;
    }
    
    public void setMahang(String mahang) {
        this.mahang = mahang;
    }
    public String getTenhang() {
        return this.tenhang;
    }
    
    public void setTenhang(String tenhang) {
        this.tenhang = tenhang;
    }
    public Set<Laptop> getLaptops() {
        return this.laptops;
    }
    
    public void setLaptops(Set<Laptop> laptops) {
        this.laptops = laptops;
    }




}


