package model;
// Generated Nov 25, 2019 8:40:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private String makh;
     private String tenkh;
     private String dienthoai;
     private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

    public Khachhang() {
    }

	
    public Khachhang(String makh) {
        this.makh = makh;
    }
    public Khachhang(String makh, String tenkh, String dienthoai, Set<Hoadon> hoadons) {
       this.makh = makh;
       this.tenkh = tenkh;
       this.dienthoai = dienthoai;
       this.hoadons = hoadons;
    }
   
    public String getMakh() {
        return this.makh;
    }
    
    public void setMakh(String makh) {
        this.makh = makh;
    }
    public String getTenkh() {
        return this.tenkh;
    }
    
    public void setTenkh(String tenkh) {
        this.tenkh = tenkh;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public Set<Hoadon> getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set<Hoadon> hoadons) {
        this.hoadons = hoadons;
    }




}


