package model;
// Generated Nov 21, 2019 2:59:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private int mahd;
     private Khachhang khachhang;
     private Nhanvien nhanvien;
     private String trangthai;
     private Set<Hoadonchitiet> hoadonchitiets = new HashSet<Hoadonchitiet>(0);

    public Hoadon() {
    }

	
    public Hoadon(int mahd, Khachhang khachhang, Nhanvien nhanvien) {
        this.mahd = mahd;
        this.khachhang = khachhang;
        this.nhanvien = nhanvien;
    }
    public Hoadon(int mahd, Khachhang khachhang, Nhanvien nhanvien, String trangthai, Set<Hoadonchitiet> hoadonchitiets) {
       this.mahd = mahd;
       this.khachhang = khachhang;
       this.nhanvien = nhanvien;
       this.trangthai = trangthai;
       this.hoadonchitiets = hoadonchitiets;
    }
   
    public int getMahd() {
        return this.mahd;
    }
    
    public void setMahd(int mahd) {
        this.mahd = mahd;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(String trangthai) {
        this.trangthai = trangthai;
    }
    public Set<Hoadonchitiet> getHoadonchitiets() {
        return this.hoadonchitiets;
    }
    
    public void setHoadonchitiets(Set<Hoadonchitiet> hoadonchitiets) {
        this.hoadonchitiets = hoadonchitiets;
    }




}


